#!/bin/bash
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# liquid prompt
[[ $- = *i* ]] && source $HOME/personal/liquidprompt/liquidprompt

# alias df='pydf'
# ls: illegal option -- - caused by --color=auto no longer applicable to mac
alias ll='ls -lhAFHG'
alias ls='ls -FHG'
alias mkdir='mkdir -pv'
alias ps='ps auxf'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias wget='wget -c'
alias ddu='du -h -d 1 | sort -hr'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

mcd() { mkdir -p '$1'; cd '$1';}

# Python
# alias python='python3'

# Git
alias gs='git status'
alias ga='git add'
alias gA='git add --all'
alias gaa='git add -a'
alias gcm='git commit -m'
alias gca='git commit -a -m'
alias gpush='git push'
alias gdiff='git diff'

alias \
s!='sudo !!' \
copydir='pwd | tr -d '\n' | pbcopy' \
src='source $ZDOTDIR/.zshrc' \
hsi='history | grep -i'

copyfile(){
[ -n "$1" ]\
&& CPFILE="$@"\
&& readlink -f "$CPFILE" | tr -d '\n' | pbcopy
}

if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# virtualenvwrapper
if [ -f $HOME/Library/Python/3.9/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME=$HOME/.virtualenvs
    export PROJECT_HOME=$HOME/Devel
    source $HOME/Library/Python/3.9/bin/virtualenvwrapper.sh                                     
fi


###
# OS Specific
###
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  alias clip='xsel -b'
elif [[ "$OSTYPE" == "darwin"* ]]; then
  alias clip='pbcopy'
  # Brew Specific completion
  [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
  # Add keys
  ssh-add --apple-use-keychain
  # -K deprecated in MacOS 12.0, replaced with --apple-use-keychain
  # ssh-add -K
else
  echo "Error, Undetected OS, cannot alias clip program"
fi

pathaddback() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}

pathaddfront() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="$1${PATH:+":$PATH"}"
    fi
}

# FIND PROCESS
function p(){
        ps aux | grep -i $1 | grep -v grep
}

function ka(){

    cnt=$( p $1 | wc -l)  # total count of processes found
    klevel=${2:-15}       # kill level, defaults to 15 if argument 2 is empty

    echo -e "\nSearching for '$1' -- Found" $cnt "Running Processes .. "
    p $1

    echo -e '\nTerminating' $cnt 'processes .. '

    ps aux  |  grep -i $1 |  grep -v grep   | awk '{print $2}' | xargs sudo kill -klevel
    echo -e "Done!\n"

    echo "Running search again:"
    p "$1"
    echo -e "\n"
}

# pathaddfront $HOME/bin/
pathaddfront $HOME/.local/bin/
pathaddback /opt/homebrew/anaconda3/bin/
pathaddfront $HOME/.bin/

# Rosetta
alias brewr="arch -x86_64 /usr/local/bin/brew $@"
alias leg="arch -x86_64 $@"

# Enable vim in zsh
bindkey -v ; export KEYTIMEOUT=1
