#!/bin/bash
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# liquid prompt
[[ $- = *i* ]] && source $HOME/personal/liquidprompt/liquidprompt

# alias df='pydf'
# ls: illegal option -- - caused by --color=auto no longer applicable to mac
alias ll='ls -lhAFHG'
alias ls='ls -FHG'
alias mkdir='mkdir -pv'
alias ps='ps auxf'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias wget='wget -c'
alias ddu='du -h -d 1 | sort -hr'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias killwandb="ps aux|grep wandb|grep -v grep | awk '{print $2}'|xargs kill -9"

mcd() { mkdir -p '$1'; cd '$1';}

# Python
# alias python='python3'

# Git
alias gs='git status'
alias ga='git add'
alias gA='git add --all'
alias gaa='git add -a'
alias gcm='git commit -m'
alias gca='git commit -a -m'
alias gpush='git push'
alias gdiff='git diff'

# Vim
alias rmswp='find . -type f -name "*.sw?" -delete'
alias swp='find . -type f -name "*.sw?"'

alias \
s!='sudo !!' \
copydir='pwd | tr -d '\n' | pbcopy' \
src='source $ZDOTDIR/.zshrc' \
hsi='history | grep -i'

copyfile(){
[ -n "$1" ]\
&& CPFILE="$@"\
&& readlink -f "$CPFILE" | tr -d '\n' | pbcopy
}

# Slurm
# format="\"%8i %8g %9u %5P %30j %2t %12M %12l %5D %3C %10R %10b\""
format="\"%16i %4u %10P %8j %2t %8M %8l %5D %3C %6m %16R %17b\""
flags="-S +i -o ${format}"
alias q="squeue -u $USER ${flags}"  # my jobs
alias qa="squeue -p long-cpu -a ${flags}" # Jobs in the parition I care
alias qaa="squeue -a ${flags}" # Jobs from all paritions
alias qlb="squeue -p lab-bengioy -a ${flags}" # Jobs from all paritions
export DPATH=/network/scratch/a/alexander.tong/se3_diffusion/dem/
alias cdd="cd $DPATH"
###############
# SINFO aliases
###############
# Detailed sinfo
alias si="sinfo -o '%8P %10n %.11T %.4c %.8z %.6m %12G %10l %10L %10O %20E' -S '-P'"

# SSTAT alias to get information about your RUNNING jobs
# Usage: sst <jobid>
#     OR sst <jobid>.batch (if you use SBATCH and do not use SRUN inside)
alias sst='sstat --format=JobID,NTasks,AveCPU,AveCPUFreq,AveRSS,MaxRSS -j'

alias sc='cat $HOME/scratch/`ls -t $HOME/scratch | head -n1`'
alias st='tail -f $HOME/scratch/`ls -t $HOME/scratch | head -n1`'


if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# virtualenvwrapper
if [ -f $HOME/Library/Python/3.9/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME=$HOME/.virtualenvs
    export PROJECT_HOME=$HOME/Devel
    source $HOME/Library/Python/3.9/bin/virtualenvwrapper.sh                                     
fi

###
# OS Specific
###
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  alias clip='xsel -b'
  #  export LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_sss.so.2
elif [[ "$OSTYPE" == "darwin"* ]]; then
  alias clip='pbcopy'
  # Brew Specific completion
  [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
  # Add keys
  ssh-add --apple-use-keychain
  # -K deprecated in MacOS 12.0, replaced with --apple-use-keychain
  # ssh-add -K
  # Rosetta
  alias brewr="arch -x86_64 /usr/local/bin/brew $@"
  alias leg="arch -x86_64 $@"

  # Enable vim in zsh
  bindkey -v ; export KEYTIMEOUT=1
else
  echo "Error, Undetected OS, cannot alias clip program"
fi

pathaddback() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}

pathaddfront() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="$1${PATH:+":$PATH"}"
    fi
}

# FIND PROCESS
function p(){
        ps aux | grep -i $1 | grep -v grep
}

function ka(){

    cnt=$( p $1 | wc -l)  # total count of processes found
    klevel=${2:-15}       # kill level, defaults to 15 if argument 2 is empty

    echo -e "\nSearching for '$1' -- Found" $cnt "Running Processes .. "
    p $1

    echo -e '\nTerminating' $cnt 'processes .. '

    ps aux  |  grep -i $1 |  grep -v grep   | awk '{print $2}' | xargs sudo kill -klevel
    echo -e "Done!\n"

    echo "Running search again:"
    p "$1"
    echo -e "\n"
}

# pathaddfront $HOME/bin/
pathaddfront $HOME/.local/bin/
pathaddback /opt/homebrew/anaconda3/bin/
pathaddfront $HOME/.bin/

alias quota=disk-quota
#alias quota='beegfs-ctl --cfgFile=/etc/beegfs/home.d/beegfs-client.conf --getquota --uid $USER'
alias sa='salloc --gres=gpu:1 -c 2 --mem=16G -t 12:00:00 --partition=unkillable'
alias sac='salloc -c 4 --mem=16G -t 12:00:00 --partition=main-cpu'
alias sacc='salloc -c 4 --mem=32G -t 12:00:00 --partition=main-cpu'
alias sahuge='salloc -c 4 --mem=128G -t 12:00:00 --partition=long-cpu'
alias sab='salloc -c 1 --mem=8G -t 12:00:00 --partition=main-cpu'
# Max configurations for unkillable and main
alias msa='salloc --gres=gpu:a100l:1 -c 6 --mem=32G -t 48:00:00 --partition=unkillable'
alias mmsa='salloc --gres=gpu:a100l:2 -c 8 --mem=48G -t 48:00:00 --partition=main'
alias ymsa='salloc --gres=gpu:a100l:1 -c 16 --mem=256G -t 48:00:00 --partition=lab-bengioy'
alias ymsa2='salloc --gres=gpu:a100l:2 -c 16 --mem=256G -t 7-00:00:00 --partition=lab-bengioy'
alias mhmsa='salloc --gres=gpu:a100l:1 -c 4 --mem=24G -t 48:00:00 --partition=main'
alias mmmsa='salloc --gres=gpu:a100l:2 -c 8 --mem=48G -t 48:00:00 --partition=long'
alias msahuge='salloc --gres=gpu:a100l:4 -c 64 --mem=1023G -t 7-00:00:00 --partition=lab-bengioy,long'
alias msashort='salloc --gres=gpu:a100l:4 -c 24 --mem=127G -t 3:00:00 --partition=lab-bengioy,long'
alias sa4='salloc --gres=gpu:4 -c 16 --mem=64G -t 48:00:00 --partition=long --exclude=cn-g[005-012,017-026]'
alias sa2='salloc --gres=gpu:2 -c 8 --mem=48G -t 48:00:00 --partition=long --exclude=cn-g[005-012,017-026]'
alias sa1='salloc --gres=gpu:1 -c 4 --mem=24G -t 48:00:00 --partition=long'
alias ssa1='salloc --gres=gpu:1 -c 1 --mem=12G -t 48:00:00 --partition=long'

function load_mc(){
  module purge
  module load miniconda/3
  conda env list
}

function load_ts(){
  cd $HOME/trainable_symmetry/
  module purge
  module load miniconda/3
  conda activate ts_cpu
}

function load_op(){
  cd $HOME/openproblems-comp/
  module purge
  module load miniconda/3
  conda activate openproblems
}

function load_src(){
  load_mc
  cd $HOME/mila/2_causality/structure_recovery/
  conda activate structure_recovery_cpu
}

function load_sr(){
  load_mc
  cd $HOME/mila/2_causality/structure_recovery/
  conda activate structure_recovery
}

function load_ti(){
  load_mc
  cd $HOME/trajectory-inference
  conda activate trajectory-inference
}

function load_se3(){
  load_mc
  cd $HOME/se3_diffusion/
  conda activate $HOME/scratch/se3
}

function load_ai(){
  cd $HOME/active_inference/runner/
  micromamba activate $HOME/scratch/ai2-env
  # eval "$(python src/train.py -sc install=bash)"
}

function load_dem(){
  cd $HOME/DEM/
  micromamba activate $HOME/scratch/dem-env
  # eval "$(python src/train.py -sc install=bash)"
}

function load_tnet(){
  load_mc
  cd $HOME/TrajectoryNet/
  micromamba activate $HOME/scratch/tnet10
  # eval "$(python src/train.py -sc install=bash)"
}
function load_mdlm(){
  load_mc
  cd $HOME/mdlm/
  micromamba activate $HOME/scratch/mdlm-env/
  # eval "$(python src/train.py -sc install=bash)"
}

function load_ff(){
  load_mc
  cd $HOME/frame-flow/
  micromamba activate $HOME/scratch/frameflow-env/
  # eval "$(python src/train.py -sc install=bash)"
}
function runj(){
  export JUPYTER_RUNTIME_DIR=${SLURM_TMPDIR}
  ssh -f -N -R 35795:localhost:35795 ${SLURM_SUBMIT_HOST}
  jupyter lab --no-browser --port=35795
}
function runj2(){
  export JUPYTER_RUNTIME_DIR=${SLURM_TMPDIR}
  ssh -f -N -R 35796:localhost:35796 ${SLURM_SUBMIT_HOST}
  jupyter lab --no-browser --port=35796
}
PATH=$PATH:/home/mila/a/alexander.tong/dl_binder_design/include/silent_tools/
HISTSIZE=20000
HISTFILESIZE=20000

